# Generated by Django 5.2.17 on 2026-08-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedchannel',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='publisheddeal',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='publisheddeal',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='publisheddeal',
            name='telegram_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
