# Generated by Django 5.2.17 on 2026-08-20 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0003_telegrambot_telegramuser_publishedchannel_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegrambot',
            options={},
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'ordering': ['-last_seen_at']},
        ),
        migrations.AddField(
            model_name='publishedchannel',
            name='allow_direct_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='publishedchannel',
            name='auto_allow_users',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_seen_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='status',
            field=models.CharField(choices=[('allowed', 'Allowed'), ('blocked', 'Blocked')], default='allowed', max_length=20),
        ),
        migrations.AlterField(
            model_name='publisheddeal',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='bot_token',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ChannelUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('allowed', 'Allowed'), ('blocked', 'Blocked')], default='allowed', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='publisher.publishedchannel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_memberships', to='publisher.telegramuser')),
            ],
            options={
                'ordering': ['-joined_at'],
                'constraints': [models.UniqueConstraint(fields=('channel', 'user'), name='unique_channel_user')],
            },
        ),
        migrations.CreateModel(
            name='UserDestinationPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_message', models.BooleanField(default=True)),
                ('can_publish', models.BooleanField(default=False)),
                ('is_allowed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='publisher.publishedchannel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_permissions', to='publisher.telegramuser')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'destination'), name='unique_user_destination_permission')],
            },
        ),
    ]
