# Generated by Django 5.2.17 on 2026-08-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0004_alter_telegrambot_options_alter_telegramuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedchannel',
            name='auto_publish_deals',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='publishedchannel',
            name='send_welcome_message',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='publishedchannel',
            name='welcome_message',
            field=models.TextField(blank=True, default='👋 Welcome {name}!\n\nYou are now connected with our Telegram community.\n\n🎁 Stay tuned for the latest deals and offers!'),
        ),
    ]
