# Generated by Django 5.2.17 on 2026-08-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0005_publishedchannel_auto_publish_deals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisheddeal',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=20),
        ),
    ]
