# Generated by Django 5.2.17 on 2026-08-23 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0008_deal_price_deal_rating'),
        ('publisher', '0006_alter_publisheddeal_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('bot_created', 'Bot Created'), ('bot_updated', 'Bot Updated'), ('destination_created', 'Destination Created'), ('destination_updated', 'Destination Updated'), ('user_first_seen', 'User First Seen'), ('user_joined', 'User Joined'), ('user_left', 'User Left'), ('user_allowed', 'User Allowed'), ('user_blocked', 'User Blocked'), ('deal_published', 'Deal Published'), ('deal_publish_failed', 'Deal Publish Failed')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='publisher.telegrambot')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='deals.deal')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='publisher.publishedchannel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='publisher.telegramuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
