# Generated by Django 5.2.17 on 2026-08-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0007_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='channeluser',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channeluser',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('allowed', 'Allowed'), ('blocked', 'Blocked'), ('left', 'Left')], default='active', max_length=20),
        ),
    ]
