# Generated by Django 5.2.17 on 2026-08-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField()),
                ('date', models.DateTimeField()),
                ('content', models.TextField(blank=True, null=True)),
                ('product_link', models.TextField(blank=True, null=True)),
                ('image_path', models.TextField(blank=True, null=True)),
                ('channel', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('processed', 'Processed'), ('published', 'Published'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='new', max_length=20)),
            ],
            options={
                'db_table': 'deals',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('channel', 'message_id'), name='unique_channel_message')],
            },
        ),
    ]
