# Generated by Django 5.2.17 on 2026-08-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_category_deal_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
