# Generated by Django 5.2.17 on 2026-08-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_deal_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='keywords',
        ),
        migrations.AlterField(
            model_name='category',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
