# Generated by Django 5.2.17 on 2026-08-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_remove_deal_keywords_alter_category_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='keywords',
            field=models.TextField(blank=True, help_text='Comma separated keywords', null=True),
        ),
        migrations.AlterModelTable(
            name='category',
            table='deal_categories',
        ),
    ]
