# Generated by Django 5.2.17 on 2026-08-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_remove_deal_category_category_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='keywords',
            field=models.TextField(blank=True, help_text='Comma-separated keywords', null=True),
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
    ]
