# Generated by Django 5.2.17 on 2026-08-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_remove_category_is_active_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Product/deal price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Product rating, e.g. 4.50', max_digits=3, null=True),
        ),
    ]
