# Generated by Django 5.2.17 on 2026-08-21 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0008_deal_price_deal_rating'),
        ('publisher', '0005_publishedchannel_auto_publish_deals_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('deal_limit', models.PositiveIntegerField(default=5)),
                ('interval_seconds', models.PositiveIntegerField(default=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_deals', models.PositiveIntegerField(default=0)),
                ('published_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishing_schedules', to='publisher.publishedchannel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledPublishItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('published_record_id', models.PositiveIntegerField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_publish_items', to='deals.deal')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scheduler.publishingschedule')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('schedule', 'deal'), name='unique_schedule_deal')],
            },
        ),
    ]
