# Generated by Django 5.2.17 on 2026-08-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishingschedule',
            name='skipped_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
